
CREATE TABLE IF NOT EXISTS `expense_transaction` (`ID` int(11) NOT NULL,  `TRANSACTION_DATE` datetime DEFAULT NULL,  `AMOUNT` double DEFAULT NULL,  `VAT_PAID` double DEFAULT NULL,  `CREDIT_CHECK` tinyint(1) NOT NULL DEFAULT '0',  `REMARK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,  `TRANSACTION_TYPE_ID` int(11) DEFAULT NULL,`VENDOR_ID` int(11) DEFAULT NULL) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `expense_transaction_type` (  `ID` int(11) NOT NULL, `NAME` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,`TYPE` int(11) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `expense_transaction` ADD PRIMARY KEY (`ID`), ADD KEY `EXP_VENDOR_ID` (`VENDOR_ID`), ADD KEY `EXP_TRANSACTION_TYPE_ID` (`TRANSACTION_TYPE_ID`);


ALTER TABLE `expense_transaction_type` ADD PRIMARY KEY (`ID`);


ALTER TABLE `expense_transaction` MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;


ALTER TABLE `expense_transaction` ADD CONSTRAINT `EXP_TRANSACTION_TYPE_ID` FOREIGN KEY (`TRANSACTION_TYPE_ID`) REFERENCES `expense_transaction_type` (`ID`),ADD CONSTRAINT `EXP_VENDOR_ID` FOREIGN KEY (`VENDOR_ID`) REFERENCES `inventory_vendor` (`ID`);


ALTER TABLE `inventory_transaction` ADD `VAT_PAID` double DEFAULT NULL;

ALTER TABLE `inventory_transaction` ADD  `CREDIT_CHECK` tinyint(1) NOT NULL DEFAULT '0';

ALTER TABLE `inventory_transaction` CHANGE `QUANTITY` `QUANTITY` DOUBLE NULL DEFAULT NULL;

ALTER TABLE `inventory_transaction` CHANGE `REMARK` `REMARK` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL;


ALTER TABLE `inventory_vendor` ADD `PHONE` varchar(15) DEFAULT NULL;

ALTER TABLE `inventory_vendor` ADD  `EMAIL` varchar(30) DEFAULT NULL;

ALTER TABLE `inventory_vendor` ADD  `ADDRESS` varchar(15) DEFAULT NULL;